#!/bin/bash
set -euo pipefail

# 1. 載入環境變數
if [ -f .env ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    # 忽略註解與空行
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue

    if [[ "$line" == *"="* ]]; then
      key="${line%%=*}"
      value="${line#*=}"
      # 去除首尾引號與空白
      key=$(echo "$key" | xargs)
      value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
      export "$key"="$value"
    fi
  done <.env
fi

USER_NAME=${USER_NAME:-sa}
SA_PASSWORD=${SA_PASSWORD:-}
CONTAINER_NAME="mssql-eris"

if [ -z "$SA_PASSWORD" ]; then
  echo "未在環境變數或 .env 中找到 SA_PASSWORD。"
  read -rs -p "請輸入 SA 密碼: " SA_PASSWORD
  echo ""
fi

# 2. 自動偵測容器工具 (podman 或 docker)
CONTAINER_TOOL=""
if command -v podman >/dev/null 2>&1 && podman ps --filter name="$CONTAINER_NAME" --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
  CONTAINER_TOOL="podman"
elif command -v docker >/dev/null 2>&1 && docker ps --filter name="$CONTAINER_NAME" --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
  CONTAINER_TOOL="docker"
else
  # 容器沒運行，檢查安裝了哪個工具
  if command -v podman >/dev/null 2>&1; then
    CONTAINER_TOOL="podman"
  elif command -v docker >/dev/null 2>&1; then
    CONTAINER_TOOL="docker"
  else
    echo "❌ 錯誤: 系統未安裝 podman 或 docker。"
    exit 1
  fi
fi

# 3. 檢查容器是否運行
if ! $CONTAINER_TOOL ps --filter name="$CONTAINER_NAME" --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
  echo "❌ 錯誤: 容器 '$CONTAINER_NAME' 並未運行。"
  echo "💡 請先使用以下指令啟動容器："
  echo "   $CONTAINER_TOOL-compose up -d  (或 docker compose up -d)"
  exit 1
fi

echo "🔍 使用容器工具: $CONTAINER_TOOL"
echo "🔍 正在連接 SQL Server 取得資料庫清單..."

# 4. 取得使用者資料庫清單 (排除系統資料庫)
DB_LIST_RAW=$($CONTAINER_TOOL exec -i "$CONTAINER_NAME" sqlcmd -S localhost -U "$USER_NAME" -P "$SA_PASSWORD" -h -1 -Q "SET NOCOUNT ON; SELECT name FROM sys.databases WHERE name NOT IN ('master', 'tempdb', 'model', 'msdb')" 2>/dev/null || true)

if [ -z "$DB_LIST_RAW" ]; then
  echo "❌ 錯誤: 無法連線至 SQL Server 或密碼錯誤。請檢查 SA_PASSWORD 是否正確。"
  exit 1
fi

# 清理格式（去除 CR 換行符號、首尾空白，並排除空行）
DB_LIST=$(echo "$DB_LIST_RAW" | tr -d '\r' | awk '{$1=$1;print}' | grep -v '^$')

# 5. 決定備份目標
TARGET_DBS=""
if [ $# -gt 0 ]; then
  # 如果有參數，檢查該資料庫是否存在
  INPUT_DB="$1"
  if echo "$DB_LIST" | grep -qx "$INPUT_DB"; then
    TARGET_DBS="$INPUT_DB"
  else
    echo "❌ 錯誤: 資料庫 '$INPUT_DB' 不存在於 SQL Server 中。"
    echo "📋 目前可用的資料庫清單："
    echo "$DB_LIST" | sed 's/^/ - /'
    exit 1
  fi
else
  # 如果無參數，進入互動選單
  echo "=========================================="
  echo "請選擇要備份的資料庫："
  echo "=========================================="

  # 將資料庫清單轉為陣列
  IFS=$'\n' read -rd '' -a dbs <<<"$DB_LIST" || true

  select opt in "${dbs[@]}" "=== 備份所有資料庫 ===" "=== 取消 ==="; do
    case "$opt" in
    "=== 取消 ===")
      echo "已取消備份。"
      exit 0
      ;;
    "=== 備份所有資料庫 ===")
      TARGET_DBS="$DB_LIST"
      break
      ;;
    *)
      if [ -n "$opt" ]; then
        TARGET_DBS="$opt"
        break
      else
        echo "⚠️  選項無效，請輸入正確的數字。"
      fi
      ;;
    esac
  done
fi

# 6. 執行備份流程
for db in $TARGET_DBS; do
  echo "----------------------------------------------------"
  echo "⚙️  正在處理資料庫: $db"

  # 建立備份目錄 (在 Host 端)
  BACKUP_DIR="./backups/$db"
  mkdir -p "$BACKUP_DIR"

  # 處理舊備份檔案 (latest.bak -> latest.bak.old)
  if [ -f "$BACKUP_DIR/latest.bak" ]; then
    echo "📦 發現已存在的備份檔，將舊備份命名為 latest.bak.old..."
    mv -f "$BACKUP_DIR/latest.bak" "$BACKUP_DIR/latest.bak.old"
  fi

  # 在容器內執行 SQL 備份指令
  # 容器內的備份目錄是 /var/opt/mssql/backups/$db/latest.bak
  echo "💾 執行 SQL Server 備份指令..."
  $CONTAINER_TOOL exec -i "$CONTAINER_NAME" sqlcmd -S localhost -U "$USER_NAME" -P "$SA_PASSWORD" -Q "
        BACKUP DATABASE [$db]
        TO DISK = N'/var/opt/mssql/backups/$db/latest.bak'
        WITH FORMAT, INIT, SKIP, NOREWIND, NOUNLOAD, STATS = 10;
    "

  # 產生 metadata.json
  echo "📝 產生/更新 metadata.json..."
  cat <<EOF >"$BACKUP_DIR/metadata.json"
{
  "database": "$db",
  "sqlserverVersion": "2022",
  "source": "backup.sh",
  "createdAt": "$(date +%Y-%m-%d)",
  "description": "Backup of $db database generated by backup.sh"
}
EOF

  echo "✅ 資料庫 '$db' 備份成功！"
  echo "📂 備份檔位置: $BACKUP_DIR/latest.bak"
done

echo "=========================================="
echo "🎉 所有備份程序已完成。"
echo "=========================================="
